# Generated by Django 5.1.6 on 2025-03-20 13:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        max_length=255, verbose_name="Project Name & Block No."
                    ),
                ),
                (
                    "flight_no_day",
                    models.CharField(max_length=255, verbose_name="Flight No. Day"),
                ),
                ("operators", models.CharField(max_length=255)),
                ("pilot", models.CharField(max_length=255)),
                ("flight_date", models.DateField()),
                ("departure", models.CharField(max_length=255)),
                ("overlap", models.FloatField(verbose_name="Overlap (%)")),
                ("gsd", models.CharField(max_length=255, verbose_name="GSD (cm)")),
                ("aircraft", models.CharField(default="Unknown", max_length=255)),
                (
                    "navigation_system",
                    models.CharField(default="Unknown", max_length=255),
                ),
                ("mount", models.CharField(default="Unknown", max_length=255)),
                ("imu", models.CharField(default="Unknown", max_length=255)),
                ("camera", models.CharField(default="Unknown", max_length=255)),
                (
                    "serial_no",
                    models.CharField(max_length=255, verbose_name="Serial No"),
                ),
                ("focal_length", models.CharField(default="Unknown", max_length=255)),
                (
                    "gps_data_logging_time",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(0, 0),
                        null=True,
                        verbose_name="GPS Data Logging Time",
                    ),
                ),
                (
                    "sun_angle",
                    models.CharField(
                        default="Unknown", max_length=255, verbose_name="Sun Angle"
                    ),
                ),
                ("none", models.CharField(default="None", max_length=255)),
                (
                    "internal_pos_data_code",
                    models.CharField(default="Unknown", max_length=255),
                ),
                ("aperture", models.CharField(default="Unknown", max_length=255)),
                ("shutter_speed", models.CharField(default="Unknown", max_length=255)),
                ("iso", models.CharField(default="Unknown", max_length=255)),
                ("fmc", models.CharField(default="Unknown", max_length=255)),
                ("ibd", models.CharField(default="Unknown", max_length=255)),
                (
                    "engine_start",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(0, 0),
                        null=True,
                        verbose_name="Engine Start",
                    ),
                ),
                (
                    "start_movement",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(0, 0),
                        null=True,
                        verbose_name="Start Movement",
                    ),
                ),
                (
                    "take_off",
                    models.CharField(
                        default="Unknown", max_length=255, verbose_name="Take off"
                    ),
                ),
                (
                    "landing",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(0, 0),
                        null=True,
                        verbose_name="Landing",
                    ),
                ),
                (
                    "stop_movement",
                    models.TimeField(
                        blank=True,
                        default=datetime.time(0, 0),
                        null=True,
                        verbose_name="Stop Movement",
                    ),
                ),
                (
                    "shutdown",
                    models.CharField(
                        default="Unknown", max_length=255, verbose_name="Shutdown"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlightObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_of_entry", models.TimeField()),
                (
                    "time_of_end",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "turning_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Turning Time"
                    ),
                ),
                ("run", models.IntegerField(blank=True, null=True)),
                ("heading", models.IntegerField(blank=True, null=True)),
                ("dir", models.CharField(max_length=50, verbose_name="Dir.")),
                (
                    "photo_numbers",
                    models.CharField(max_length=255, verbose_name="Photo Numbers"),
                ),
                ("qty", models.IntegerField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "flight_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="flight_data.flightdata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather", models.CharField(blank=True, max_length=255)),
                ("remarks", models.TextField(blank=True)),
                ("signature", models.CharField(blank=True, max_length=255)),
                (
                    "flight_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_info",
                        to="flight_data.flightdata",
                    ),
                ),
            ],
        ),
    ]
