# Generated by Django 5.1.6 on 2025-02-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlightData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flight_date", models.DateField(blank=True, null=True)),
                ("weather", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("signature", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
