# Generated by Django 5.1.6 on 2025-03-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flightdata",
            old_name="none",
            new_name="none_type",
        ),
        migrations.RenameField(
            model_name="flightobservation",
            old_name="dir",
            new_name="direction",
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="aircraft",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="aperture",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="camera",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="fmc",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="focal_length",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="ibd",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="imu",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="internal_pos_data_code",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="iso",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="mount",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="navigation_system",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="flightdata",
            name="shutter_speed",
            field=models.CharField(default="Unknown", max_length=255, null=True),
        ),
    ]
